resources:
  - name: myGitrepo
    type: gitRepo
    integration: github
    versionTemplate:     
      sourceName: vijayreddy1991/w16
      branch: test
    buildOnCommit: true
    buildOnTagPush: false
    
jobs:
  - name: window2016
    type: runSh
    runtime:
      nodePool: dynamic__x86_64__WindowsServer_2016__c4_large
    steps:
      - IN: myGitrepo
      - TASK: 
         script:
         - pushd $(shipctl get_resource_state "myGitrepo")
         - dir
         - docker build -t drydockw16test:master -f C:\Users\Administrator\Shippable\Runtime\8a5956d6-9831-4a47-ab95
    -fcef53a6d0fc\build\IN\myGitrepo\gitRepo\Dockerfile .
         - popd
      
      - TASK:
          runtime:
            options:
              imageName: "drydockw16test"
              imageTag: master
          script:  
            - git --version
            - python --version
            - node --version
            - git lfs version
            - ruby --version
            - gcloud version
            - aws --version
            - az --version
            - jfrog --version
            - terraform -version
            - packer --version
            - jq --version
            - kubectl version --client
            - docker --version
            - java --version
            - choco list
            - choco --version
